### ISSUE TITLE
Colour Scheme Switcher

### ISSUE THREAD

**Issue by krisanalfa** [benweier/Themr#12]
This package is great. But, I only able to change the theme, not with the colour scheme. Would you mind to add new feature so I can switch the colour scheme too while I switch the theme?
<img width="1680" alt="screen shot 2015-10-05 at 1 17 53 pm" src="https://cloud.githubusercontent.com/assets/3734729/10274053/84115410-6b63-11e5-9516-17047d069678.png">

**Comment by benweier** [comment]
Hi @krisanalfa You can change your colour scheme with my complimentary plugin [Schemr](https://github.com/benweier/Schemr) (also available through Package Control)

**Comment by krisanalfa** [comment]
Hi @benweier, thanks for your fast response. I tried your package and it works like a charm. It solves my problem. But, IMHO, it will be great if you merge these two packages. So we can **combine** our theme + scheme into one "favourite display", and of course we can switch over them easily.

**Comment by benweier** [comment]
Unfortunately I don't have any plans to combine the functionality of the two plugins. From the very beginning I did this intentionally to give users the choice of modular complimentary features they will use, instead of a single monolithic plugin that isn't fully utilised.

I suggest trying my older [Present Command](https://github.com/benweier/PresetCommand) plugin that will "batch" settings together into a single command. It does require some manual editing to get set up since I'm not actively developing it. While it hasn't been updated recently it still works in ST2 and ST3, and I will respond and fix issues if they come up.

**Comment by krisanalfa** [comment]
Hi, thanks man, you're my hero. I can do this, now:


```js
[
    { "keys": ["super+shift+d"], "command": "preset_command_by_name", "args": { "name": "Dark" } },
    { "keys": ["super+shift+l"], "command": "preset_command_by_name", "args": { "name": "Light" } }
]
```

And this is my preset:

```js
{
    "presets": [
        {
            "name": "Dark",
            "description": "Join the dark side",
            "settings":
            {
                "theme": "Material-Theme-Darker.sublime-theme",
                "color_scheme": "Packages/Material Theme/schemes/Material-Theme-Darker.tmTheme"
            }
        },
        {
            "name": "Light",
            "description": "Into the light, I command thee!",
            "settings":
            {
                "theme": "Material-Theme-Lighter.sublime-theme",
                "color_scheme": "Packages/Material Theme/schemes/Material-Theme-Lighter.tmTheme"
            }
        }
    ]
}
```
